name: Publish to PyPI

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Upgrade pip version
      run: |
        python -m pip install --upgrade pip
      
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    
    - name: Test version with unittest
      run:
        python -m unittest
    
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel
        
#     - name: Publish distribution 📦 to PyPI
#       uses: pypa/gh-action-pypi-publish@master
#       with:
#         password: ${{ secrets.PYPI_API_TOKEN }}   
