name: Publish to TestPyPI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Upgrade pip version
      run: |
        python -m pip install --upgrade pip
      
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    
    - name: Test version with unittest
      run:
        python -m unittest
    
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel
        
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/     
